version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./app:/var/www
    depends_on:
      - app
    networks:
      - app-network

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    volumes:
      - ./app:/var/www
      - ./supervisor:/etc/supervisor/conf.d
    ports:
      - "9080:9000"
    environment:
      QUEUE_CONNECTION: redis
    depends_on:
      - redis
    networks:
      - app-network

  redis:
    image: redis:alpine
    ports:
      - "6380:6379"
    volumes:
      - ./redis-data:/data
    networks:
      - app-network

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: hy2wfgs5ggfdt654
      MYSQL_DATABASE: checker
      MYSQL_USER: checker
      MYSQL_PASSWORD: vfwn09efghaisdhf0!g
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
    networks:
      - app-network

  queue:
    build:
      context: ./app
      dockerfile: Dockerfile
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    command: supervisord -c /etc/supervisor/conf.d/laravel-worker.conf
    volumes:
      - ./app:/var/www
      - ./supervisor:/etc/supervisor/conf.d
    networks:
      - app-network
    depends_on:
      - db

volumes:
  mysql-data:
  redis-data:

networks:
  app-network:
    driver: bridge
